"""Initialisation complete

Revision ID: 05c7e7a2df9d
Revises: 
Create Date: 2026-08-09 22:25:23.422017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c7e7a2df9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('filieres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filieres_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_filieres_nom'), ['nom'], unique=True)

    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('niveau', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matieres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matieres_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_matieres_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matieres_niveau'), ['niveau'], unique=False)
        batch_op.create_index(batch_op.f('ix_matieres_nom'), ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_matieres_semestre'), ['semestre'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('matiere_filiere',
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('matiere_id', 'filiere_id', 'semestre')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('specialite', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=255), nullable=True),
    sa.Column('activation_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_token'),
    sa.UniqueConstraint('matricule')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('enseignements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('professeur_id', 'matiere_id', 'semestre', name='uq_enseignement')
    )
    with op.batch_alter_table('enseignements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enseignements_id'), ['id'], unique=False)

    op.create_table('inscriptions',
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'matiere_id', 'semestre')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('type_note', sa.String(length=20), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.Column('session', sa.Enum('NORMALE', 'RATTRAPAGE', 'REPRISE', name='sessionnote'), nullable=False),
    sa.Column('date_saisie', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('commentaire', sa.String(length=255), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)

    op.create_table('resultats_semestre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.Column('moyenne_semestre', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('a_passe_rattrapage', sa.Boolean(), nullable=False),
    sa.Column('est_officiel', sa.Boolean(), nullable=False),
    sa.Column('date_calcul', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultats_semestre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultats_semestre_id'), ['id'], unique=False)

    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    with op.batch_alter_table('resultats_semestre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultats_semestre_id'))

    op.drop_table('resultats_semestre')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    op.drop_table('inscriptions')
    with op.batch_alter_table('enseignements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enseignements_id'))

    op.drop_table('enseignements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('matiere_filiere')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('matieres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matieres_semestre'))
        batch_op.drop_index(batch_op.f('ix_matieres_nom'))
        batch_op.drop_index(batch_op.f('ix_matieres_niveau'))
        batch_op.drop_index(batch_op.f('ix_matieres_id'))
        batch_op.drop_index(batch_op.f('ix_matieres_code'))

    op.drop_table('matieres')
    with op.batch_alter_table('filieres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filieres_nom'))
        batch_op.drop_index(batch_op.f('ix_filieres_id'))

    op.drop_table('filieres')
    # ### end Alembic commands ###
