"""nom_de_la_migration

Revision ID: 5ecd75bcd5be
Revises: 43b2be562d1e
Create Date: 2026-08-20 19:06:18.385736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ecd75bcd5be'
down_revision: Union[str, Sequence[str], None] = '43b2be562d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions_annuelles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.Column('credits_valides', sa.Integer(), nullable=False),
    sa.Column('credits_total', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('PASSE', 'ENJAMBEMENT', 'REDOUBLEMENT', name='decisionpassage'), nullable=False),
    sa.Column('date_decision', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('commentaire', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etudiant_id', 'annee_universitaire', name='uq_decision_annuelle_etudiant_annee')
    )
    op.create_index(op.f('ix_decisions_annuelles_id'), 'decisions_annuelles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_annuelles_id'), table_name='decisions_annuelles')
    op.drop_table('decisions_annuelles')
    # ### end Alembic commands ###
