"""Initialisation complète

Revision ID: 60dfef0c94ad
Revises: 
Create Date: 2026-08-07 12:33:56.304957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dfef0c94ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filieres_id'), 'filieres', ['id'], unique=False)
    op.create_index(op.f('ix_filieres_nom'), 'filieres', ['nom'], unique=True)
    op.create_table('matieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('niveau', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matieres_code'), 'matieres', ['code'], unique=True)
    op.create_index(op.f('ix_matieres_id'), 'matieres', ['id'], unique=False)
    op.create_index(op.f('ix_matieres_niveau'), 'matieres', ['niveau'], unique=False)
    op.create_index(op.f('ix_matieres_nom'), 'matieres', ['nom'], unique=False)
    op.create_index(op.f('ix_matieres_semestre'), 'matieres', ['semestre'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('matricule', sa.String(length=50), nullable=True),
    sa.Column('specialite', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activation_token', sa.String(length=255), nullable=True),
    sa.Column('activation_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activation_token'),
    sa.UniqueConstraint('matricule')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('matiere_filiere',
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('matiere_id', 'filiere_id', 'semestre')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.Column('type_note', sa.String(length=20), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.Column('date_saisie', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('commentaire', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_table('matiere_filiere')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_matieres_semestre'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_nom'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_niveau'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_id'), table_name='matieres')
    op.drop_index(op.f('ix_matieres_code'), table_name='matieres')
    op.drop_table('matieres')
    op.drop_index(op.f('ix_filieres_nom'), table_name='filieres')
    op.drop_index(op.f('ix_filieres_id'), table_name='filieres')
    op.drop_table('filieres')
    # ### end Alembic commands ###
