"""Ajout de la table matiere_filiere

Revision ID: 77f9eb2ebece
Revises: aa8049e25d05
Create Date: 2026-08-09 01:34:01.618912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f9eb2ebece'
down_revision: Union[str, Sequence[str], None] = 'aa8049e25d05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
