"""Modification filiere_id pour heritage par filiere

Revision ID: 85a16150d329
Revises: 05c7e7a2df9d
Create Date: 2026-08-10 00:21:24.592620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85a16150d329'
down_revision: Union[str, Sequence[str], None] = '05c7e7a2df9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
