"""Ajout des tables resultats_semestre, enseignement, inscription et du champ session dans notes

Revision ID: bc7f5d7e9418
Revises: 60dfef0c94ad
Create Date: 2026-08-07 17:46:12.482679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7f5d7e9418'
down_revision: Union[str, Sequence[str], None] = '60dfef0c94ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enseignements',
    sa.Column('professeur_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.ForeignKeyConstraint(['professeur_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('professeur_id', 'matiere_id', 'semestre')
    )
    op.create_table('inscriptions',
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('etudiant_id', 'matiere_id', 'semestre')
    )
    op.create_table('resultats_semestre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etudiant_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.Column('annee_universitaire', sa.String(length=20), nullable=False),
    sa.Column('moyenne_semestre', sa.Float(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('a_passe_rattrapage', sa.Boolean(), nullable=False),
    sa.Column('est_officiel', sa.Boolean(), nullable=False),
    sa.Column('date_calcul', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('date_validation', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['etudiant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultats_semestre_id'), 'resultats_semestre', ['id'], unique=False)
    op.drop_table('matiere_filiere')
    op.add_column('notes', sa.Column('session', sa.Enum('NORMALE', 'RATTRAPAGE', 'REPRISE', name='sessionnote'), nullable=False))
    op.add_column('notes', sa.Column('coefficient', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'coefficient')
    op.drop_column('notes', 'session')
    op.create_table('matiere_filiere',
    sa.Column('matiere_id', sa.INTEGER(), nullable=False),
    sa.Column('filiere_id', sa.INTEGER(), nullable=False),
    sa.Column('semestre', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('matiere_id', 'filiere_id', 'semestre')
    )
    op.drop_index(op.f('ix_resultats_semestre_id'), table_name='resultats_semestre')
    op.drop_table('resultats_semestre')
    op.drop_table('inscriptions')
    op.drop_table('enseignements')
    # ### end Alembic commands ###
