"""Creation matiere_filiere

Revision ID: e10e239efb64
Revises: 77f9eb2ebece
Create Date: 2026-08-09 01:40:41.788706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10e239efb64'
down_revision: Union[str, Sequence[str], None] = '77f9eb2ebece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matiere_filiere',
    sa.Column('matiere_id', sa.Integer(), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['matiere_id'], ['matieres.id'], ),
    sa.PrimaryKeyConstraint('matiere_id', 'filiere_id', 'semestre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matiere_filiere')
    # ### end Alembic commands ###
