"""add niveau_actuel to users

Revision ID: ef0130f09d9b
Revises: 465bd3b791f7
Create Date: 2026-08-20 12:08:29.392382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef0130f09d9b'
down_revision: Union[str, Sequence[str], None] = '465bd3b791f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('niveau_actuel', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'niveau_actuel')
    # ### end Alembic commands ###
